import type { Metadata } from "next"
import type { ReactNode } from "react"

import { Inter } from "next/font/google"

import { ThemeProvider } from "next-themes"

import "./globals.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

type RootLayoutProps = {
  children: ReactNode
}

const font = Inter({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["cyrillic"],
  variable: "--font-inter",
})

const RootLayout = ({ children }: RootLayoutProps) => {
  return (
    <html suppressHydrationWarning lang="ru">
      <body className={`${font.variable} font-sans min-h-dvh antialiased`}>
        <ThemeProvider
          enableSystem
          enableColorScheme
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}

export default RootLayout